
services:
  db:
    image: postgres:15-alpine
    container_name: foodtrack-database
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: foodtrack_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend-spring-boot:
    build:
      context: ./backend-spring-boot
      dockerfile: Dockerfile
    container_name: foodtrack-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/foodtrack_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      MY_AI_SERVICE_URL: http://ai_microservice:8085
    ports:
      - "8083:8083"

  ai_microservice:
    build:
      context: ./ml-recognition-model
      dockerfile: Dockerfile
    container_name: foodtrack-ai-microservice
    ports:
      - "8085:8085"
      

volumes:
  postgres_data:

networks:
  foodtrack-network:
    driver: bridge